CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(30) NOT NULL,
	emial VARCHAR(100) UNIQUE NOT NULL,
	role VARCHAR(20) NOT NULL
);

CREATE TABLE products (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	price NUMERIC(10, 2) NOT NULL,
	quantity INT NOT NULL,
	seller_id INT NOT NULL REFERENCES users(id)
);